### ISSUE TITLE
printDemon error

### ISSUE THREAD

**Issue by chvryT** [BC-SECURITY/Invoke-PrintDemon#2]
when i run the .ps1 script,i get
"printDemon error"
"printDemon cannot print My C#.NET RAW Document",and i cannot get the system.if i copy ualapi.dll the target machine,t get nothing

**Comment by Hubbl3** [comment]
@chvryT you are supposed to get that error. You have to restart the computer for this to work. The privesc works based on the fact that the .shd file (your print job that's in error) loses user attribution when spooler is restarted and impersonates SYSTEM when that attribution is lost

**Comment by chvryT** [comment]
thanks for your response.could you tell me the version of your target
machine,my  target machine was built on windows 10 business,and i
cannot elevate
permissions after run the .ps1.

Hubble <notifications@github.com> 于2020年5月19日周二 下午9:44写道：

**Comment by chvryT** [comment]
i read the .ps1,maybe i found the reason why i got failed,the target machine seems cannot print bytes to c:\windows\sysytem\ualapi.dll.so it cannot start Fax service.but i donot know why.if i copy the ualapi.dll to system32 as an administrator,i cannot get the system permissions after i run the .ps in empire.that upset me.
have a nice day!

**Comment by Hubbl3** [comment]
@chvryT. Make sure that you have the most recent version pulled down.

As I said before this will not work without the victim machine being restarted. So steps to make printdemon work.
1. Run the .ps1
2. Restart the target machine 

Do not worry about the printer being unable to write to system32 initially. This is supposed to happen. It will be able to write there after the target machine has restarted.

**Comment by chvryT** [comment]
@Hubbl3 .Thanks very much.After i restart the victim machine,i can see ualapi.dll.And i maybe find a problem.When i restart the victim machine,the .ps1 will start Fax,but it cannot success,so it always cannot get system permissions .So i delete the codes about "sc.exe start Fax...",and run "sc.exe start Fax" by cmd command after restarting the victim machine.And then use nc.exe to connect 9299,i will get the system permissions.Just like https://github.com/ionescu007/faxhell.
Anyway,thanks very much for your response.
Have a nice day.
